### ISSUE TITLE
Tip: CSS Organization

### ISSUE THREAD

**Issue by melissamcewen** [ViktorNfa/ColmarAcademy#3]
Everyone has their own preference for writing/organizing CSS. If you work on specific software or projects they might have a styleguide for this. My own personal preference is having the media queries in with the styles like

```css

#footer {
  border-top: 1px solid #c0c0c0;
  display: flex;
  justify-content: space-between;
  padding: 24px;
  font-family: "Open Sans", sans-serif;

  @media only screen and (max-width: 760px) {   
     display: block;
      font-size: .75rem;
  }

  
}
```

Of course that's just one way to do it. Personally I like it better, it helps me envision the individual areas and how they work in different breakpoints, but other people prefer the approach you use for different reasons.
